### ISSUE TITLE
sol redirection/amtterm

### ISSUE THREAD

**Issue by Frank-Steiner** [Openwsman/wsmancli#10]
Hi,

I'm aware that amttern is not part of openwsman, but I didn't find a
better place to look for people who know about vPro/amt and Linux,
so maybe someone here can help.

I guess amtterm is known to all of you, and it still seems to be
the only non-GUI program for accessing the SOL console in Linux
(and seemingly the only working client at all, I just tested
  meshCommander, and it's SOL implemenration is a nightmare...).

Now, amtterm seems to have stopped working with amt 12.x. It still
is fine on our 11.x clients, but on our new Optiplex 7070 with
amt 12.x it cannot authenticate

amtterm: NONE -> CONNECT (connection to host)
ipv4 192.168.1.43 [192.168.1.43] 16994 open
amtterm: CONNECT -> INIT (redirection initialization)
amtterm: INIT -> AUTH (session authentication)
amtterm: AUTH -> ERROR (failure)
amtterm: ERROR: session authentication failed

All other tools like wsman, wsamt, amtctrl still work fine, kvm
with any vnc client does, too, just amtterm doesn't.

I already asked Gerd, but he doesn't have vPro hardware and no time
to look into amtterm again.

So I wonder if someone here might have the skills and would be willing
to either take a look at the amtterm code (it's really quite short)
or write some cli SOL client as replacement, as part of the wsmancli
package. This could make a lot people happy in future, because the
more 12.x hosts are sold, the more linux users will run into this problem.

cu,
Frank

**Comment by chelmuth** [comment]
Today I discovered the same issue with AMT 14. Has anybody a working alternative to or patch for amtterm to use AMT SOL with version 14?

@Frank-Steiner do you know more details about what's missing in amtterm to authenticate successfully? Could it be that there's a configuration option to switch back to *old-style* authentication?

**Comment by Frank-Steiner** [comment]
Sorry, my fault, I should have added here that I found a patch for amtterm at https://senseless.info/downloads.html which works with the new vPro/AMT stuff. It implements the needed SSL code. I sent this link to Gerd Hoffmann, the maintainer of amtterm, but unfortunately he didn't react, so you have to compile it yourself.
Currently there is a problem in either the vPro code or some Bios (like HP 800 G5) that will cause the SOL port not being initialized if the host is rebooted or power off/on in a certain way. So it might happen that you won't see the grub2 screen in amtterm because grub2 cannot init the port itself, only the linux kernel can. HP and Intel are currently working on a fix.

**Comment by chelmuth** [comment]
Thanks for your quick response! This will really speed up @m-stein's and my debugging with Lenovo T490.

**Comment by morph027** [comment]
Just for the record, i've extracted @Frank-Steiner s patch via archive.org's wayback machine ;)

[amtterm-digestauth-ssl.patch.tar.gz](https://github.com/Openwsman/wsmancli/files/5742033/amtterm-digestauth-ssl.patch.tar.gz)

Works for me, thank you :rocket:

Compiled a deb package for myself:

```
curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/a/amtterm/amtterm_1.4-3.dsc
curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/a/amtterm/amtterm_1.4.orig.tar.gz
curl -LO http://archive.ubuntu.com/ubuntu/pool/universe/a/amtterm/amtterm_1.4-3.debian.tar.xz
dpkg-source -x amtterm_1.4-3.dsc
cd amtterm-1.4/
patch -p1 < ../amtterm-digestauth-ssl.patch
dpkg-source --commit
dpkg-buildpackage -us -uc
```

**Comment by kkaempf** [comment]
Release 1.7 from https://github.com/kraxel/amtterm has this included.

**Comment by Frank-Steiner** [comment]
And it works fine, thanks for the info!

**Comment by jerryabramson** [comment]
I don't know if this was the right approach, but I forked this project a couple of years ago, and have made some progress on supporting Mutual TLS and Insecure SSL (help from frank).

The repo is here:
https://github.com/jerryabramson/amtterm_ssl

**Comment by pasikarkkainen** [comment]
@jerryabramson Thanks a lot! amtterm_ssl seems to work for me with AMT14.
