### ISSUE TITLE
Run wsman command on RHEL7.X, but get authentication.verify_peer error

### ISSUE THREAD

**Issue by dreamonsea** [Openwsman/wsmancli#6]
# wsman identify -h localhost -P 5986 -u root -p iforgot --debug=6

Jun 24 04:01:23  cl->authentication.verify_peer: 1
Jun 24 04:01:23  Error = 43 (A libcurl function was given a bad argument); curl_easy_setopt(CURLOPT_SSL_VERIFYHOST) failed
Connection failed. response code = 0
# rpm -qa|grep wsman

wsmancli-2.3.0-4.el7.x86_64
openwsman-server-2.3.6-13.el7.x86_64
libwsman1-2.3.6-13.el7.x86_64
openwsman-client-2.3.6-13.el7.x86_64
# systemctl status openwsmand.service

openwsmand.service - Openwsman WS-Management Service
   Loaded: loaded (/usr/lib/systemd/system/openwsmand.service; disabled)
   Active: active (running) since Wed 2015-06-24 03:35:25 EDT; 28min ago
 Main PID: 142809 (openwsmand)
   CGroup: /system.slice/openwsmand.service
           â””â”€142809 /usr/sbin/openwsmand -S

Jun 24 03:35:25 gha2.usa.hp.com systemd[1]: PID file /var/run/wsmand.pid not readable (yet?) after start.
Jun 24 03:35:25 gha2.usa.hp.com systemd[1]: Started Openwsman WS-Management Service.

I check the source of wsmancli and found the error should be caused by cl->authentication.verify_peer = 1. But I can't find the exact meaning of this verify_peer=1.

**Comment by dreamonsea** [comment]
On the other system, we got similar errors.
# rpm -qa|grep wsman
wsmancli-2.3.0-4.el7.x86_64
libwsman1-2.3.6-13.el7.x86_64
openwsman-server-2.3.6-13.el7.x86_64
# wsman enumerate http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ComputerSystem -h localhost  --username root --password XXXX --port 5986 --debug=6 -V v --cacert=/etc/openwsman/serverkey.pem
Jun 24 04:21:41  cl->authentication.verify_peer: 0
Jun 24 04:21:41  Error = 43 (A libcurl function was given a bad argument); curl_easy_setopt(CURLOPT_SSL_VERIFYHOST) failed
Connection failed. response code = 0

**Comment by jjacquay712** [comment]
Having the same issue, were you able to find a solution?

**Comment by uprt** [comment]
just add --noverifyhost to command line arguments.
