### ISSUE TITLE
compilation error: initialization of ‘char’ from ‘void *’

### ISSUE THREAD

**Issue by c3be** [Openwsman/wsmancli#9]
Compilation of file 'wsman.c' raises following error  (at least with gcc version 8.20):
_error: initialization of ‘char’ from ‘void *’ makes integer from pointer without a cast [-Werror=int-conversion]_

The error comes from the use of `NULL` value for `short_name` field of `u_option_entry_t` in line 227.
It should be replaced by the value 0.

 
[wsman.c.diff.txt](https://github.com/Openwsman/wsmancli/files/2544362/wsman.c.diff.txt)

**Comment by kkaempf** [comment]
Fixed in 53b61bb9
